language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "pip install -U pip"
  - "pip install scikit-learn"
  - "pip install scipy"
# command to run tests
script: pytest